import { motion, type Variants } from "framer-motion";
import { Link } from "react-router-dom";
import { BigDemo } from "../components/BigDemo";
import { ProofSplit } from "../components/ProofSplit";
import { HeroSection } from "../components/HeroSection";
import { HowItWorks } from "../components/HowItWorks";
import { TimeMachine } from "../components/TimeMachine";
import { PhonePeek } from "../components/PhonePeek";
import { StatsBar } from "../components/StatsBar";
import { ClosingCTA } from "../components/ClosingCTA";

const EASE = [0.22, 1, 0.36, 1] as const;

const inView: Variants = {
  hidden: { opacity: 0, y: 18 },
  show: { opacity: 1, y: 0, transition: { duration: 0.7, ease: EASE } },
};

const TOOLS_BY_SUITE = [
  {
    suite: "Learning Suite",
    tag: "01",
    body: "Active recall. Classroom-shaped study material.",
    tools: [
      { name: "Quiz Generator", note: "Scored interactive quiz with feedback after every answer." },
      { name: "Flashcards", note: "Flippable Q-and-A deck — drill on the metro, on the bed, before sleep." },
      { name: "Math Solver", note: "Step-by-step worked solutions with formatted equations." },
      { name: "Worksheet Generator", note: "Printable practice sheets with sections and answer space." },
    ],
  },
  {
    suite: "Visual Lab",
    tag: "02",
    body: "Concepts that only land when they animate.",
    tools: [
      { name: "Interactive Presentation", note: "Click-through slide explainer that stays inside the workspace." },
      { name: "Process Animation", note: "SVG-based motion for cycles, processes, and transformations." },
      { name: "Interactive Simulation", note: "Sandboxed live model with sliders for variables." },
      { name: "Data Visualization", note: "Line, bar, or pie chart from raw numbers, with hover detail." },
    ],
  },
  {
    suite: "Build & Export",
    tag: "03",
    body: "Real deliverables you can actually hand in.",
    tools: [
      { name: "Interactive Web App", note: "Self-contained HTML mini-tool you can open in a browser." },
      { name: "Python IDE", note: "In-browser editor + console + run history." },
      { name: "PDF Notes", note: "A4 document with markdown, math, and tables." },
      { name: "Google Doc Draft", note: "Doc-ready content you can copy into Docs in one click." },
      { name: "Google Sheet Draft", note: "Sheet preview with CSV download." },
      { name: "PowerPoint Builder", note: "Real downloadable .pptx file." },
      { name: "Canva Design Spec", note: "Creative brief — palette, type, layout, copy." },
    ],
  },
];

export function HomePage() {
  return (
    <>
      {/* HERO — animated cinematic intro */}
      <HeroSection />

      {/* BIG DEMO — one prompt, four artifacts */}
      <BigDemo />

      {/* HOW IT WORKS — pinned 3-step */}
      <HowItWorks />

      {/* PROOF SPLIT — animated side-by-side comparison */}
      <ProofSplit />

      {/* TIME MACHINE — emotional moments */}
      <TimeMachine />

      {/* PHONE PEEK — pinned phone with cycling artifacts */}
      <PhonePeek />

      {/* STATS — counter-animated */}
      <StatsBar />

      {/* TOOLS — full directory */}
      <section className="border-b border-hairline bg-[var(--color-surface-alt)] py-24 md:py-32">
        <div className="mx-auto w-full max-w-[var(--container-page)] px-6 md:px-8">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-15%" }}
            transition={{ duration: 0.7, ease: EASE }}
            className="mb-16 max-w-[44ch]"
          >
            <h2 className="font-medium tracking-display text-[clamp(28px,4vw,52px)] leading-[1.05] text-[var(--color-ink)]">
              Fifteen tools.{" "}
              <span className="font-serif italic font-normal text-[var(--color-ink-dim)]">
                Pick the output, not the prompt.
              </span>
            </h2>
            <p className="mt-5 max-w-[58ch] text-[15.5px] leading-[1.65] text-[var(--color-ink-dim)]">
              The full toolkit a serious student would otherwise stitch together from twelve different apps. Generated by AI, finished by you.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 gap-16 lg:grid-cols-3 lg:gap-12">
            {TOOLS_BY_SUITE.map((s, si) => (
              <motion.div
                key={s.suite}
                initial={{ opacity: 0, y: 14 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-10%" }}
                transition={{ duration: 0.6, ease: EASE, delay: si * 0.06 }}
                className="flex flex-col gap-3"
              >
                <div className="flex items-baseline gap-2">
                  <span className="text-[12.5px] text-[var(--color-muted)]">Suite {s.tag}</span>
                </div>
                <h3 className="text-[22px] font-medium tracking-[-0.012em] text-[var(--color-ink)]">
                  {s.suite}
                </h3>
                <p className="text-[13.5px] text-[var(--color-ink-dim)]">{s.body}</p>
                <ul className="mt-3 flex flex-col">
                  {s.tools.map((t, ti) => (
                    <motion.li
                      key={t.name}
                      initial={{ opacity: 0, x: -4 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true, margin: "-10%" }}
                      transition={{ duration: 0.45, ease: EASE, delay: 0.04 + ti * 0.04 }}
                      className="border-t border-hairline py-3.5"
                    >
                      <div className="text-[14.5px] font-medium tracking-[-0.01em] text-[var(--color-ink)]">
                        {t.name}
                      </div>
                      <div className="mt-1 text-[13px] leading-[1.55] text-[var(--color-ink-dim)]">
                        {t.note}
                      </div>
                    </motion.li>
                  ))}
                </ul>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* AUDIENCES — quiet list */}
      <section className="border-b border-hairline py-24 md:py-32">
        <div className="mx-auto w-full max-w-[920px] px-6 md:px-8">
          <motion.div
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, margin: "-15%" }}
            variants={inView}
            className="mb-14 max-w-[44ch]"
          >
            <h2 className="font-medium tracking-display text-[clamp(28px,4vw,52px)] leading-[1.1] text-[var(--color-ink)]">
              Built for people who learn by{" "}
              <span className="font-serif italic font-normal text-[var(--color-ink-dim)]">
                making.
              </span>
            </h2>
          </motion.div>

          <div className="divide-y divide-[var(--color-hairline)]">
            {[
              { k: "Students", b: "Boards, JEE, NEET. Move between understanding, practice, and submission without switching apps." },
              { k: "Independent learners", b: "Same tools without the classroom wrapper. Turn a chapter into revision material on a Sunday morning." },
              { k: "Educators and tutors", b: "Lesson prep at speed. Quizzes, worksheets, decks, PDF handouts — editable and exportable." },
            ].map((row, i) => (
              <motion.div
                key={row.k}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-10%" }}
                transition={{ duration: 0.6, ease: EASE, delay: 0.04 + i * 0.05 }}
                className="grid grid-cols-1 items-baseline gap-3 py-7 md:grid-cols-[200px_1fr] md:gap-12"
              >
                <h3 className="text-[16px] font-medium tracking-[-0.012em] text-[var(--color-ink)]">
                  {row.k}
                </h3>
                <p className="max-w-[58ch] text-[14.5px] leading-[1.6] text-[var(--color-ink-dim)]">
                  {row.b}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* STORY TEASE */}
      <section className="border-b border-hairline bg-[var(--color-surface-alt)] py-20 md:py-28">
        <div className="mx-auto w-full max-w-[760px] px-6 md:px-8">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-15%" }}
            transition={{ duration: 0.8, ease: EASE }}
            className="flex flex-col items-start gap-5"
          >
            <span className="text-[13px] text-[var(--color-muted)]">Why we're doing this</span>
            <p className="font-serif italic text-[clamp(22px,3vw,32px)] leading-[1.4] text-[var(--color-ink)]">
              We're three students who just finished CBSE Class 12. We had ChatGPT on our phones for boards. It explained things. It didn't help us study. We're building Topperly so the next batch doesn't have the same problem.
            </p>
            <Link
              to="/story"
              className="text-[14px] text-[var(--color-ink-dim)] underline-offset-[6px] transition-colors hover:text-[var(--color-ink)] hover:underline"
            >
              Read the full story →
            </Link>
          </motion.div>
        </div>
      </section>

      {/* CTA — cinematic close */}
      <ClosingCTA />
    </>
  );
}
